### ISSUE TITLE
Which Firefox version was it tested against?

### ISSUE THREAD

**Issue by volth** [rahiel/archiveror#1]
I tries to install in for latest mainstream Firefox (36.0) and Nightly (39) with no success.
On Nightly Firefox, a new toolbar button has been added. Nothing happens when the button is clicked.
On mainstream Firefox even no toolbar button appear.

**Comment by rahiel** [comment]
I tested the addon with Firefox 35 and 36. If you click the button, you will get the archive link in your clipboard so you can paste it somewhere, nothing else is done. I don't know why the button doesn't appear in 36, can you see the icon at Firefox's Customization?

I've changed the behaviour so it will also open a new tab with the archive page. Could you remove the extension and reinstall it from here <https://addons.mozilla.org/en-US/firefox/addon/archiveror/> ?

**Comment by volth** [comment]
I do not see the icon at Firefox's Customization in both browsers. 
Although in 39 I see it on the toolbar.

**Comment by rahiel** [comment]
The icon appears automatically after install in a new Firefox 36 profile. Maybe there is a conflict with one of your other add-ons? Other than suggesting to reinstall the add-on I don't know how to solve this.

**Comment by rahiel** [comment]
@volth are you using Windows 8? I tested it with Firefox 36 on Windows 8 and the icon indeed didn't appear.

**Comment by volth** [comment]
Windows 7

**Comment by rahiel** [comment]
@volth could you check if this issue has been fixed with the latest version of the addon?

**Comment by rahiel** [comment]
When Firefox was set to "Never remember history" at the privacy settings, the archiveror icon would not show up because it wasn't enabled in private browsing mode. This was fixed in  [this commit ](https://github.com/rahiel/archiveror/commit/405cb8ec74296e63942de366a555e0417a5855f6).
