### ISSUE TITLE
Allow multiple archiving sites at once

### ISSUE THREAD

**Issue by rory** [rahiel/archiveror#12]
Currently you can only choose one archiving site. It would be cool if you could select more than one option, and if you click the button to archive, it would open as many tabs as needed to archive the page.

In a way, this would make it easier to have multiple copies of a page, which further reduces the chance of link rot. :)

**Comment by rahiel** [comment]
Good idea, thanks! I'll add this.

**Comment by rahiel** [comment]
@rory, this is now available in the version for Chrome, Firefox will follow.

**Comment by rahiel** [comment]
This feature is now available on Firefox and Chromium.
