### ISSUE TITLE
Click on the button to manually archive on all the different archiving services?

### ISSUE THREAD

**Issue by orschiro** [rahiel/archiveror#14]
Dear @rahiel,

Suggestion:

In the options, I set to archive to all three available archiving services. 

However, on clicking the button manually, it only opens one new tab to archive on `archive.is`. 

Why doesn't it open two more tabs to also back up on `archive.org` and `Webcitation`?

**Comment by rahiel** [comment]
Did you click the "Save" button at the end of the options?

**Comment by orschiro** [comment]
@rahiel my bad.

I did not see the save button...

Thank you!
