### ISSUE TITLE
[Bug] Ignoring Archive Save Preferences

### ISSUE THREAD

**Issue by stephenjudge** [rahiel/archiveror#17]
I have found this after most recent update to the Firefox extension.

Actions
1. In Extension Options I set the chosen archive site to be Internet Archive
2. I save my settings and close the extenstion settings page.
3. I return to the settings page and find the chosen archive site has returned to the default site: archive.is

Expected Result:
1. When setting the chosen archive site to be Internet Archive it should remain so.

Without a fix for this I can no longer use Archiveror as I only want to archive to the Internet Archive.

**Comment by rahiel** [comment]
For now you can archive pages on the Internet Archive by: right-clicking a page -> Archive -> archive.org

I can't reproduce the bug you've described. When you click the "save" button at the options, does the text "Options saved." appear next to it? What version of Firefox are you using?

**Comment by rahiel** [comment]
I've now tested on Firefox Quantum 59 and Archiveror 0.8, I still can't reproduce this bug.

Feel free to reopen this issue if you can reproduce this on the latest firefox/archiveror.
