### ISSUE TITLE
Options: Save locally *and* archive online on save?

### ISSUE THREAD

**Issue by TjWallas** [rahiel/archiveror#18]
Hello,

I was wondering if it is possible to extend the options menu so that Archiveror both:
* Locally saves a page as MHTML for offline use then,
* Submits the page for online archiving using the selected services in the options menu.

.. When the extension's button is clicked.

**Comment by rahiel** [comment]
Good suggestion, I'll look at it.

**Comment by rahiel** [comment]
This is now available in version 0.9. At the options, select which archiving methods you'd like to use (choose from the online archiving services and the local MHTML option). Then make all these archives all at once when you click the "Archive Now" button in the extension's popup.

**Comment by TjWallas** [comment]
@rahiel :+1:

Is it possible to auto-archive bookmarks to wayback machine? So far, the only options for auto-archiving bookmarks are MHTML and archive.is .

**Comment by rahiel** [comment]
> Is it possible to auto-archive bookmarks to wayback machine? So far, the only options for auto-archiving bookmarks are MHTML and archive.is .

This is now possible in version 0.11.
