### ISSUE TITLE
If the bookmark is removed, is it supposed to remove the local file?

### ISSUE THREAD

**Issue by Tiggy626** [rahiel/archiveror#19]
That appears to be the current behavior. If that is intended, I would like to request an option to prevent the deletion of local files.

Thank you,
Tiggy626

**Comment by rahiel** [comment]
Hey @Tiggy626,

This is indeed the intended functionality. The local archive structure mirrors the browser's bookmark structure. 

Could you explain how you would use this option? Do you often delete bookmarks you've made after a long period of time? Could you instead use manual archiving?

**Comment by Tiggy626** [comment]
I don't delete bookmarks after a long period of time, but I am
currently attempting to clean up my bookmarks and I was planning on
just visiting the previously bookmarked page then deleting the
bookmark,

I was intending to use this to automatically save pages that I didn't
need to keep track of, but just to have one local copy for future
reference. 

For example, instructions for a craft project I want to do at some
future time, that has all the information I need to do that project. I
wouldn't need to have the bookmark cluttering up my bookmark menus if
I have the instructions. Another example is reading a story on Archive
of our Own. I bookmark the story, read it, then delete the bookmark. I
would like to keep the story on my PC to read at some other time.

I don't want to keep bookmarks I no longer need, but I would still
like to keep the saved page.

Yes, I could use manual archiving, and that would probably be the best
option, I was just attempting to duplicate the functionality of a
no-longer supported program Wysigot. There isn't anything on the
market that does what it did, so I am frantically trying to come up
with workarounds.

I hate it when a program I use daily stops functioning because it is
no longer being updated.

**Comment by rahiel** [comment]
Thanks for your explanation.

> Yes, I could use manual archiving, and that would probably be the best option, I was just attempting to duplicate the functionality of a no-longer supported program Wysigot. There isn't anything on the market that does what it did, so I am frantically trying to come up with workarounds.

OK, tell me if you're satisfied with manual archiving. Otherwise I can easily implement the requested option if you like.

**Comment by rahiel** [comment]
I'm assuming you're satisfied with manual archiving. Closing this issue, feel free to open new ones if you encounter other issues.
