### ISSUE TITLE
Automatically archive certain bookmarks 

### ISSUE THREAD

**Issue by heytxz** [rahiel/archiveror#20]
I really like the function named automatically archive bookmarks!

But do you think it is better if only archive certain bookmarks or folder?

**Comment by rahiel** [comment]
I think *all* bookmarks are precious, so all bookmarks are archived now. For online archiving users don't waste space and the current bookmark archive service only archives a page if it isn't already previously captured. For users using local archiving, I expect they have enough disk space to spare.

You can always disable automatic archiving of bookmarks at the options and manually archive whichever pages you like.

Do you experience a problem with the current automatic archiving?

**Comment by rahiel** [comment]
Closing due to no response. Feel free to reopen this issue to continue, or to open new issues for other bugs/feature requests you have.
