### ISSUE TITLE
can I add a formated tail to the name?

### ISSUE THREAD

**Issue by rsterbal** [rahiel/archiveror#21]
Would it be possible to add an option to append the date or date time to the file name automatically?

filename-2017-10-14
filename-2017-10-14_20-42-00

**Comment by rahiel** [comment]
Good idea. I'll put this on the todo list.

**Comment by rahiel** [comment]
In 95c14c50f0279fe79b4eca93cc7ab9918035df39 I've added the date and time to filenames by default. This will be available shortly in version 0.7.
