### ISSUE TITLE
Feature Request: Add context menu option on links

### ISSUE THREAD

**Issue by Sushubh** [rahiel/archiveror#25]
Right now I can right click on a webpage to access the context menu options. But not on links. 
It would be great if I can right click on a link to archive it through this extension.

**Comment by rahiel** [comment]
Good idea, thanks for your suggestion. I've implemented this in https://github.com/rahiel/archiveror/commit/317460d1f5692119e1b932e4725612ede9536788 and released it in version 0.10. You should get this feature soon when your extensions update.
