### ISSUE TITLE
Name Conflict Overwrites MHTML Files

### ISSUE THREAD

**Issue by David-Wells99** [rahiel/archiveror#33]
If a user bookmarks multiple pages at the same time with addresses like:

https://forum.com/threads/name/#post-000
https://forum.com/threads/name/#post-001
https://forum.com/threads/name/#post-002

They all get the same name and overwrite themselves.

Reproduced on Chromium 59.

**Comment by rahiel** [comment]
Thanks for reporting this bug, I will fix this in the next release.

**Comment by rahiel** [comment]
Fix: https://github.com/rahiel/archiveror/commit/036a197258d3912b05686d68bcfcb143c42df42d.

This is fixed in version 0.12
