### ISSUE TITLE
mhtml parsing

### ISSUE THREAD

**Issue by benjamingr** [rahiel/archiveror#35]
Hey, I just published a fast mhtml parser that converts the mhtml files saved by Chrome to html and allows serving them.

Would love feedback and to know if it's relevant to you https://www.npmjs.com/package/fast-mhtml

**Comment by sterbalr** [comment]
I really wish you included this functionality in the extension.

**Comment by rahiel** [comment]
@sterbalr I don't see why this should be a part of archiveror, my extension archives pages to MHTML that can already be opened by Chromium, what would this add?

**Comment by sterbalr** [comment]
I am trying to use archiveror to make static copies of my wikis that I can use with Dropbox on iOS. Renaming the files is a challenging extra step since I have to do that on the OS.

**Comment by rahiel** [comment]
Why do you need to rename the archives? Can't you find a MHTML reader/viewer for iOS instead?

**Comment by sterbalr** [comment]
Dropbox provides a private place for me on the web and they don't seem to want to implement a mhtml viewer.

**Comment by rahiel** [comment]
Either way, this functionality is outside the scope of this extension.

**Comment by sterbalr** [comment]
I'm not sure I need anything other than a change of the name of the file extension from mhtml to html.

How many lines of code would need to be changed?

**Comment by rahiel** [comment]
> I'm not sure I need anything other than a change of the name of the file extension from mhtml to html.
> 
> How many lines of code would need to be changed?

I don't like including an extra dependency, but this change is possible. I've added a note to https://github.com/rahiel/archiveror/issues/26 to include choosing the file extension as an option.

**Comment by benjamingr** [comment]
@rahiel if you want a sticky release or to go through the code together you're welcome to use `fast-mhtml` any way you'd like. You're also (happily) welcome to "steal" the relevant files (with attribution)

**Comment by rahiel** [comment]
The issue for @sterbalr is purely with the file extension, not with the content. So it really is not necessary to integrate fast-mhtml into archiveror.

**Comment by benjamingr** [comment]
@rahiel ah, then it makes no sense - it's just a rename
