### ISSUE TITLE
Local Save - date and time not at end

### ISSUE THREAD

**Issue by chrisjj** [rahiel/archiveror#37]
https://github.com/rahiel/archiveror says

> The filenames end with the UTC date and time of when the archive was made.

but I'm seeing something else after the time e.g. "_fc03fa96"

> GitHub` - rahiel_archiveror_ Archiveror will help you preserve the webpages you love. `💾_2019-03-16_18-54_fc03fa96.mhtml

**Comment by chrisjj** [comment]
PS I see the [addition is intended](https://github.com/rahiel/archiveror/commit/036a197258d3912b05686d68bcfcb143c42df42d)  so the docs need amending.

**Comment by rahiel** [comment]
I forgot to push the readme update, added it here: https://github.com/rahiel/archiveror/commit/6525760e7dbff584541631de1153ab02a0c4069b

Thanks for reporting
