### ISSUE TITLE
"Archive Now!" button equals one other below

### ISSUE THREAD

**Issue by gloschtla** [rahiel/archiveror#38]
Why do I need two buttons for the same thing?
By default both buttons "Archive Now!" and "archive.is" do save the current page on archive.is 

What I expected: 
Only "Archive Now!" _saves_ the page in a defined online archive. 
And the buttons below don't save, but only _search_ in one of the defined online archives.

**Comment by rahiel** [comment]
> Why do I need two buttons for the same thing?
> By default both buttons "Archive Now!" and "archive.is" do save the current page on archive.is

The idea is that with "Archive Now" you can select your favorite archiving services at the options you always use and the other buttons for when it's necessary. It's true that by default "Archive Now!" is the same as another button, so in https://github.com/rahiel/archiveror/commit/5d010a9607f29d6562bbcad983823d9a9fd43e28 I've changed the default so that clicking on "Archive Now!" archives the page on both archive.is and archive.org.

>  And the buttons below don't save, but only _search_ in one of the defined online archives.

This is new feature, I've opened an issue for it at https://github.com/rahiel/archiveror/issues/40.

**Comment by arusergithub** [comment]
> What I expected:
> And the buttons below don't save, but only search in one of the defined online archives.

I didn't expect this. the buttons below are headed "Archive Online" and I read that to mean the buttons below perform and archive online, which is what they do.

**Comment by 3j9fkyahunqoxwqu** [comment]
> 
> 
> > What I expected:
> > And the buttons below don't save, but only search in one of the defined online archives.
> 
> I didn't expect this. the buttons below are headed "Archive Online" and I read that to mean the buttons below perform and archive online, which is what they do.

You can use another addon for opening/viewing archived version of websites: https://github.com/dessant/view-page-archive

**Comment by gloschtla** [comment]
> You can use another addon for opening/viewing archived version of websites: https://github.com/dessant/view-page-archive

Thank you for this great hint! Now I have replaced "Archive Now!" by "[View Page Archive & Cache](https://chrome.google.com/webstore/detail/view-page-archive-cache/hkligngkgcpcolhcnkgccglchdafcnao/)".
 SEARCHING makes more sense, because one should add an archive entry, ONLY if the entry was not found yet in archive.

**Comment by arusergithub** [comment]
> SEARCHING makes more sense, because one should add an archive entry, ONLY if the entry was not found yet in archive.

That's wrong. One may want to rearchive to record that no changes occurred or record changes that have occurred.
