### ISSUE TITLE
Improved "archives" indicator

### ISSUE THREAD

**Issue by arusergithub** [rahiel/archiveror#42]
The current "archived" indicator is an exclamation mark on an amber block:

![image](https://user-images.githubusercontent.com/50074375/56863876-d7143900-69b3-11e9-8fe0-ac1f8412d05c.png)

falsely implying a warning.

I suggest it be changed to a bold green tick (with no block).

**Comment by rahiel** [comment]
Thanks for the nice suggestion @arusergithub. In https://github.com/rahiel/archiveror/commit/44ea4c24ef41744a1a27649ed2707056551bf5cf I've changed the indicator to a check mark in a green block. I can't remove the block, by default you get a blue block, I can only change the color.

This is how it looks like:

![Screenshot_2019-10-15_11-52-15](https://user-images.githubusercontent.com/6839756/66811541-57b6f980-ef42-11e9-8f31-9980ca5d1370.png)
