### ISSUE TITLE
Improvement to archive URLs on menu

### ISSUE THREAD

**Issue by arusergithub** [rahiel/archiveror#43]
Currently any but a short archive URL widens the menu and all its buttons:

![image](https://user-images.githubusercontent.com/50074375/56863899-278b9680-69b4-11e9-8806-a57736157d85.png)

I suggest replace each archive URL by a standard-width button labelled with the archive service name, placed under a new section heading "Archives". Failing which, retain the regular width and position of the existing buttons.

**Comment by 3j9fkyahunqoxwqu** [comment]
Your suggestion is great for UI but i think it is rather bad for UX, if author implants your suggestion, we can't ensure addon working status by only watching its menu and then we must everytime that we want to check and ensure addon is working, click on every button to see if it archived or not but with what addon show now, we can check that only by watching the addon menu.

What i mean is if your suggestion will implant, we can't find out issues like #34 only by clicking on the addon menu :) but it is good for UI although.

**Comment by rahiel** [comment]
In https://github.com/rahiel/archiveror/commit/e2f56fe52b5cb4d44e0108def15284db3f672090 I've tweaked the popup appearance and now we truncate long archive links in the popup.

This is available in version 0.15, which you should soon get.

What do you guys @arusergithub @3j9fkyahunqoxwqu think of it?

**Comment by rahiel** [comment]
I'm closing this issue, feel free to reopen if you think it is not solved.

**Comment by arusergithub** [comment]
R

> This is available in version 0.15, which you should soon get.

Just to let you know, I read that to mean 0.15 would arrive automatically.
But a moment ago my installation still said 0.14.

I clicked Update and it now says 0.15,

**Comment by rahiel** [comment]
Yeah, Chrome automatically updates extensions, so you would've gotten
version 0.15 automatically simply by waiting (I don't know for how long
though or what the update schedule is)
