### ISSUE TITLE
[Feature Request | QoL] One-click archiving

### ISSUE THREAD

**Issue by BradyThe** [rahiel/archiveror#47]
First of all, thanks for having created this great extension.

As stated in the title it would be a great QoL addition to be able to archive sites when clicking the Toolbar Icon. Personally, a simple check box in the options to switch between both functionalities would be good enough for me.

**Comment by rahiel** [comment]
I like to keep the current pop-up menu, how about using the keyboard shortcut `Alt+Shift+Y`?

**Comment by BradyThe** [comment]
> 
> 
> I like to keep the current pop-up menu, how about using the keyboard shortcut `Alt+Shift+Y`?

I guess that'll do. I just realised that I replaced Shift with Ctrl unconsciously in my head every time I looked up the shortcut. Upps...

**Comment by rahiel** [comment]
Happy that works for you :)
