### ISSUE TITLE
Archiving many pages as MHTML programmingly?

### ISSUE THREAD

**Issue by zlrs** [rahiel/archiveror#50]
Assuming I want to archive 100 pages locally as MHTML, is there a way to do this in a programmable way? Can I call the Chrome plugin to do this automatically OR clone this project and do some thricks?

**Comment by rahiel** [comment]
If these 100 pages are in one bookmark folder, you can right click the bookmark folder and choose "Open all in new window" with automatic archiving enabled.

Otherwise feature request #23 covers this.

**Comment by zlrs** [comment]
Thanks. I guess this can be done by opening these pages using `selenium` or something like that with automatic archiving enabled. I will try it when I have time and post the result.
