### ISSUE TITLE
How to access bookmarks offline?

### ISSUE THREAD

**Issue by orschiro** [rahiel/archiveror#7]
Dear @rahiel,

This is by far one of the most amazing extensions.

Thank you so much!

My question is how I can access my bookmarks while being offline?

I made sure that archiving mode is set to Local, automatically archive bookmarks is checked and file access is given to local URLs. 

Thankfully,

~Robert

**Comment by rahiel** [comment]
Dear Robert, I am very happy to hear that you find this extension useful, thanks :smile:.

First visit a bookmark when online, the first time you visit it, the file will be saved locally. Archiveror's icon should then have a yellow !, click on it. It then opens the bookmark from your own harddrive, the path is shown in the URL bar, something starting with `file://...`, this shows where the file is on your computer.

Alternatively, in Chrome's downloads folder there should be a directory called "Archiveror", all local archives are in there. They are saved in .mhtml files, you can associate this filetype to be opened with Chrome, so you can then open them when offline.

**Comment by orschiro** [comment]
Dear @rahiel,

Thanks for your detailed explanation!

It all works as described by you.

The only question left: is it possible to automate the saving to file process so that Chrome doesn't ask me anymore where to save the file?

Please see below screenshot which shows that dialog that automatically pops up each time I visit a bookmark:

![nimbus-image-1459931619455-1459931837710](https://cloud.githubusercontent.com/assets/170947/14310678/8d27cb86-fbe3-11e5-802c-391ee170c8c9.png)

**Comment by rahiel** [comment]
This is due to a bug in Chromium (issue #6), it should save the files silently. A workaround is to disable "Ask where to save each file before downloading" at the settings, you have to click on "Show advanced settings" to see that. 

As a side-effect, now all your downloads are automatically saved in the Downloads folder. (Unless you right-click "Save as" something.) If you have a Google account, you could help getting this fixed by starring the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=417112.

**Comment by orschiro** [comment]
Thank you Rahiel!

  

I starred the issue and referenced it back to #6.

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 6 2016, at 1:02 pm, Rahiel Kasim &lt;notifications@github.com&gt;
wrote:  

> This is due to a bug in Chromium (issue
[#6](https://github.com/rahiel/archiveror/issues/6)), it should save the files
silently. A workaround is to disable "Ask where to save each file before
downloading" at the settings, you have to click on "Show advanced settings" to
see that.

>

> As a side-effect, now all your downloads are automatically saved in the
Downloads folder. (Unless you right-click "Save as" something.) If you have a
Google account, you could help getting this fixed by starring the issue:
<https://bugs.chromium.org/p/chromium/issues/detail?id=417112>.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/rahiel/
archiveror/issues/7#issuecomment-206311085)![](https://github.com/notification
s/beacon/AAKbw2XEQH0ylEREF1QSxx6GBna7E7i7ks5p05LBgaJpZM4IAaOf.gif)

**Comment by rahiel** [comment]
I'm closing this issue, you're welcome to open new ones for other questions. (I will test some things for that "default download location" question you had.)
