### ISSUE TITLE
Change default download location to other than Downloads

### ISSUE THREAD

**Issue by orschiro** [rahiel/archiveror#8]
Dear @rahiel,

Another related question to my first question. 

For me personally the Downloads directory is a temporary directory in which I store files usually only until I use them for something.

Archived bookmarks, however, have a permanent meaning. 

Thus I would like to store them outside the Downloads directory.

Is it technically possible to store files somewhere outside the Downloads directory?

Thankfully,

~Robert

**Comment by rahiel** [comment]
Okay, Chromium only allows extensions to save files in the `Downloads directory, this is a good security feature.

However on Linux you can trick Chromium with symbolic links to save them wherever you like:

1. Move your current `Archiveror` directory to where you want it to be.
2. Make sure there is no `Archiveror`directory in your `Downloads`.
3. Link this new location to your `Downloads` folder. In this example I moved `Archiveror` to `/home/rahiel/Documents/Archiveror`. Run in a terminal, replacing `rahiel` with your username and the first argument with where you want to store the archives (both arguments need to be full paths):

```bash
ln -s /home/rahiel/Documents/Archiveror/ /home/rahiel/Downloads
```

Now your local archives should be saved at the new location. If you look in the `Downloads` folder in your file manager, the `Archiveror` folder has an arrow, showing the actual data is somewhere else.

**Comment by orschiro** [comment]
Dear Rahiel,

  

This is a very clever workaround. I haven't actually thought of this before.

  

Thank you and problem solved! :-)

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 7 2016, at 11:12 pm, Rahiel Kasim &lt;notifications@github.com&gt;
wrote:  

> Okay, Chromium only allows extensions to save files in the `Downloads
directory, this is a good security feature.

>

> However on Linux you can trick Chromium with symbolic links to save them
wherever you like:

>

>   1. Move your current Archiveror directory to where you want it to be.

>   2. Make sure there is no Archiverordirectory in your Downloads.

>   3. Link this new location to your Downloads folder. In this example I
moved Archiveror to /home/rahiel/Documents/Archiveror. Run in a terminal,
replacing rahiel with your username and the first argument with where you want
to store the archives (both arguments need to be full paths):

>

>  
>  
>     ln -s /home/rahiel/Documents/Archiveror/ /home/rahiel/Downloads

>

> Now your local archives should be saved at the new location. If you look in
the Downloads folder in your file manager, the Archiveror folder has an arrow,
showing the actual data is somewhere else.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/rahiel/
archiveror/issues/8#issuecomment-207090460)![](https://github.com/notification
s/beacon/AAKbw30O9SDjkXPuWfCaQEasWf_dsGYOks5p1XNMgaJpZM4IA3Kp.gif)

**Comment by orschiro** [comment]
PS: Maybe nice to add this to the README or Wiki of this repository?

  

~Robert  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 8 2016, at 2:00 pm, Robert Orzanna &lt;orschiro@gmail.com&gt; wrote:  

> Dear Rahiel,

>

>  

>

> This is a very clever workaround. I haven't actually thought of this before.

>

>  

>

> Thank you and problem solved! :-)

>

>  

>

> Warmly,

>

>  

>

> ~Robert

>

>  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

>

> On Apr 7 2016, at 11:12 pm, Rahiel Kasim &lt;notifications@github.com&gt;
wrote:  

>

>> Okay, Chromium only allows extensions to save files in the `Downloads
directory, this is a good security feature.

>>

>> However on Linux you can trick Chromium with symbolic links to save them
wherever you like:

>>

>>   1. Move your current Archiveror directory to where you want it to be.

>>   2. Make sure there is no Archiverordirectory in your Downloads.

>>   3. Link this new location to your Downloads folder. In this example I
moved Archiveror to /home/rahiel/Documents/Archiveror. Run in a terminal,
replacing rahiel with your username and the first argument with where you want
to store the archives (both arguments need to be full paths):

>>

>>  
>>  
>>     ln -s /home/rahiel/Documents/Archiveror/ /home/rahiel/Downloads

>>

>> Now your local archives should be saved at the new location. If you look in
the Downloads folder in your file manager, the Archiveror folder has an arrow,
showing the actual data is somewhere else.

>>

>> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/rahiel/
archiveror/issues/8#issuecomment-207090460)![](https://github.com/notification
s/beacon/AAKbw30O9SDjkXPuWfCaQEasWf_dsGYOks5p1XNMgaJpZM4IA3Kp.gif)

**Comment by rahiel** [comment]
I'll document this on the wiki, someday. And again, you're welcome to ask more questions if they arise, maybe it will lead to a FAQ :smile:.

**Comment by orschiro** [comment]
Haha! :D

  

Well for now I am happily satisfied with having a decent way to take my
valuable bookmarks with me.

  

Thanks!

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 8 2016, at 2:51 pm, Rahiel Kasim &lt;notifications@github.com&gt;
wrote:  

> I'll document this on the wiki, someday. And again, you're welcome to ask
more questions if they arise, maybe it will lead to a FAQ ![:smile:](https
://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/rahiel/
archiveror/issues/8#issuecomment-207420739)![](https://github.com/notification
s/beacon/AAKbw_9h1cN8TPknAzDsYEIqhtxYgNUaks5p1k9LgaJpZM4IA3Kp.gif)
